name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '4.4.6'
          mongodb-port: 27017
          mongodb-username: user
          mongodb-password: password
          mongodb-db: assign1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.2

      - name: Create MongoDB User
        run: |
          mongosh admin --eval "db.createUser({ user: 'user', pwd: 'password', roles: ['userAdminAnyDatabase'] })"

      - name: Import Movies Collection
        run: |
          mongoimport --db=assign1 --collection=movie --authenticationDatabase admin --username user --password password --type=csv --file=data/movies.csv \
            --fields=movieId.int32\(\),name.string\(\),genre.string\(\),placeId.int32\(\) --columnsHaveTypes

      - name: Import Ratings Collection
        run: |
          mongoimport --db=assign1 --collection=rating --authenticationDatabase admin --username user --password password --type=csv --file=data/ratings.csv \
            --fields=userId.int32\(\),movieId.int32\(\),rating.int32\(\),timestamp.string\(\) --columnsHaveTypes

      - name: Import Users Collection
        run: |
          mongoimport --db=assign1 --collection=user --authenticationDatabase admin --username user --password password --type=csv --file=data/users.csv \
            --fields=userId.int32\(\),gender.string\(\),age.int32\(\),occupation.int32\(\),zipCode.string\(\),point.int32\(\),movieStatus.int32\(\),latitude.double\(\),longitude.double\(\),hobby.int32\(\),favoriteFood.int32\(\) --columnsHaveTypes

      - name: Import Places Collection
        run: |
          mongoimport --db=assign1 --collection=place --authenticationDatabase admin --username user --password password --type=csv --file=data/moviePlaces.csv \
            --fields=placeId.int32\(\),name.string\(\),latitude.double\(\),longitude.double\(\),hobby.int32\(\),favoriteFood.int32\(\) --columnsHaveTypes

      - name: Import Quizzes Collection
        run: |
          mongoimport --db=assign1 --collection=quiz --authenticationDatabase admin --username user --password password --type=csv --file=data/quizzes.csv --fields=quizId.int32\(\),movieId.int32\(\),quizNum.int32\(\),quizBody.string\(\),quizAnswer.int32\(\) --columnsHaveTypes

      - name: Build and run tests
        run: |
          mvn clean package
          mvn jacoco:report