name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
        with:
          mongodb-version: '4.4.6'
          mongodb-port: 27017
          mongodb-username: user
          mongodb-password: password
          mongodb-db: assign1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.2

      - name: Build and run tests
        run: mvn clean package
