name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y vim maven openjdk-17-jdk curl git

      - name: Setup Maven
        uses: stCarolas/setup-maven@v.4.5
        with:
          maven-version: 3.8.2
      
      - name: Set up MongoDB
        run: |
          wget -qO - https://www.mongodb.org/static/pgp/server-6.0.asc | sudo apt-key add -
          echo "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu focal/mongodb-org/6.0 multiverse" | sudo tee /etc/apt/sources.list.d/mongodb-org-6.0.list
          sudo apt-get update
          sudo apt-get install -y mongodb-org
          sudo systemctl start mongod
          mongosh admin --eval "db.createUser({ user: 'user', pwd: 'password', roles: ['userAdminAnyDatabase'] })"
          mongoimport --db=assign1 --collection=movie --authenticationDatabase admin --username user --password password --type=csv --file=data/movies.csv --fields=movieId.int32\(\),name.string\(\),genre.string\(\),placeId.int32\(\) --columnsHaveTypes
          mongoimport --db=assign1 --collection=rating --authenticationDatabase admin --username user --password password --type=csv --file=data/ratings.csv --fields=userId.int32\(\),movieId.int32\(\),rating.int32\(\),timestamp.string\(\) --columnsHaveTypes
          mongoimport --db=assign1 --collection=user --authenticationDatabase admin --username user --password password --type=csv --file=data/users.csv --fields=userId.int32\(\),gender.string\(\),age.int32\(\),occupation.int32\(\),zipCode.string\(\),point.int32\(\),movieStatus.int32\(\),latitude.double\(\),longitude.double\(\),hobby.int32\(\),favoriteFood.int32\(\) --columnsHaveTypes
          mongoimport --db=assign1 --collection=place --authenticationDatabase admin --username user --password password --type=csv --file=data/moviePlaces.csv --fields=placeId.int32\(\),name.string\(\),latitude.double\(\),longitude.double\(\),hobby.int32\(\),favoriteFood.int32\(\) --columnsHaveTypes
          mongoimport --db=assign1 --collection=quiz --authenticationDatabase admin --username user --password password --type=csv --file=data/quizzes.csv --fields=quizId.int32\(\),movieId.int32\(\),quizNum.int32\(\),quizBody.string\(\),quizAnswer.int32\(\) --columnsHaveTypes

      - name: Build and run tests
        run: |
          mvn jacoco:report 
          mvn clean package