name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: MongoDB in GitHub Actions
        uses: supercharge/mongodb-github-action@1.11.0
      - name: Build and Run all the test with Maven
        run: mvn clean package
